/**
 * Canonical stages permitted for AI analysis stage suggestions.
 * Strictly aligned with public.customers.stage domain.
 */
export const AI_ANALYSIS_STAGE_SUGGESTIONS = [
  'LEAD_NEW',
  'CONTACT_CYCLE_1',
  'CONTACT_CYCLE_2',
  'CONTACT_CYCLE_3',
  'UNREACHABLE',
  'SURVEY_REQUESTED',
  'SURVEY_SCHEDULED',
  'SURVEY_COMPLETED',
  'PRICE_CALCULATED',
  'NEED_INFO',
  'PRICE_OFFERED',
  'NEGOTIATING',
  'ORDER_CREATED',
  'DEPOSIT_CONFIRMED',
  'CONTRACT_SIGNED',
  'IN_PRODUCTION',
  'READY_FOR_INSTALL',
  'INSTALLING',
  'HANDOVER_COMPLETED',
  'WARRANTY_ACTIVE',
  'LOST',
  'CARE_NURTURING',
] as const;

export type AiAnalysisStageSuggestion = (typeof AI_ANALYSIS_STAGE_SUGGESTIONS)[number];

/**
 * Audit-friendly pointer to source interactions used as analysis evidence.
 * Restricted strictly to type 'INTERACTION' without content, phone, or raw payloads.
 */
export interface AiAnalysisSourceRef {
  type: 'INTERACTION';
  id: string;
}

/**
 * Safe, sanitized source item passed to the AI model.
 */
export interface AiAnalysisSource {
  interactionId: string;
  conversationId: string | null;
  channel: string;
  direction: 'INBOUND' | 'OUTBOUND';
  actorType: 'CUSTOMER' | 'SALE' | 'AI' | 'SYSTEM' | 'TECHNICIAN';
  content: string;
  createdAt: string;
}

/**
 * Non-sensitive customer metadata provided for analysis context.
 * Strictly excludes phone numbers and private credentials.
 */
export interface AiCustomerContext {
  customerId: string;
  customerCode: string;
  name: string;
  source: string;
  stage: string;
}

/**
 * Structured bounded input for the AI customer analysis engine.
 */
export interface AiAnalysisInput {
  companyId: string;
  customer: AiCustomerContext;
  sources: AiAnalysisSource[];
}

/**
 * Structured, validated output generated by an AI customer analysis model.
 * NOTE: modelVersion is NOT part of the untrusted model output.
 * Model provenance is bound strictly by the trusted host environment.
 */
export interface AiCustomerAnalysisOutput {
  summary: string;
  stageSuggestion: AiAnalysisStageSuggestion | null;
  stopReason: string | null;
  objections: string[];
  nextAction: string | null;
  confidence: number;
  evidence: string;
}

/**
 * Alias for backward compatibility.
 */
export type AiCustomerAnalysisResult = AiCustomerAnalysisOutput;

/**
 * Fully persisted record representation from public.ai_analyses.
 * Binds the validated analysis output with trusted server provenance and DB metadata.
 */
export interface AiAnalysisRecord extends AiCustomerAnalysisOutput {
  id: string;
  companyId: string;
  customerId: string;
  sourceRefs: AiAnalysisSourceRef[];
  modelVersion: string;
  createdAt: string;
}
