/**
 * Safe, sanitized outbound interaction source passed to the Sales Style model.
 * Excludes customer phone numbers, verbatim call transcripts, or private raw payloads.
 */
export interface SalesStyleSource {
  interactionId: string;
  channel: string;
  content: string;
  createdAt: string;
}

/**
 * Structured bounded input for the Sales Style Learning engine.
 */
export interface SalesStyleLearningInput {
  companyId: string;
  saleUserId: string;
  sources: SalesStyleSource[];
}

/**
 * Salutation and greeting rules extracted from Sales communication.
 */
export interface SalutationRules {
  selfReferences: string[];
  customerReferences: string[];
  commonOpenings: string[];
  notes: string[];
}

export const PREFERRED_LENGTHS = ['SHORT', 'MEDIUM', 'LONG', 'MIXED'] as const;
export type PreferredLength = (typeof PREFERRED_LENGTHS)[number];

export const EMOJI_USAGES = ['NONE', 'LOW', 'MEDIUM', 'HIGH'] as const;
export type EmojiUsage = (typeof EMOJI_USAGES)[number];

/**
 * Sentence length, rhythm, tone descriptors, and punctuation style.
 */
export interface SentenceStyle {
  preferredLength: PreferredLength;
  toneDescriptors: string[];
  emojiUsage: EmojiUsage;
  punctuationPatterns: string[];
  notes: string[];
}

/**
 * Questioning patterns, discovery approaches, and follow-up inquiry style.
 */
export interface QuestionStyle {
  commonPatterns: string[];
  discoveryApproach: string[];
  followUpApproach: string[];
  notes: string[];
}

/**
 * Representation of a specific objection situation and the stylistic response approach.
 */
export interface ObjectionApproach {
  situation: string;
  responseApproach: string;
}

/**
 * Objection handling phrasing, approaches, and stylistic guidance.
 */
export interface ObjectionStyle {
  approaches: ObjectionApproach[];
  notes: string[];
}

/**
 * Closing techniques, calls to action, and urgency expression style.
 */
export interface ClosingStyle {
  commonClosings: string[];
  callToActionPatterns: string[];
  urgencyStyle: string[];
  notes: string[];
}

/**
 * Bounded output generated by the Sales Style model.
 * STRICT FIREWALL: Must NOT contain version, modelVersion, companyId, saleUserId,
 * sourceRefs, examples, pricing rules, discount rules, or enterprise commitments.
 */
export interface SalesStyleOutput {
  salutationRules: SalutationRules;
  sentenceStyle: SentenceStyle;
  questionStyle: QuestionStyle;
  objectionStyle: ObjectionStyle;
  closingStyle: ClosingStyle;
}

/**
 * Audit-safe pointer to source interactions used for style learning.
 */
export interface SalesStyleSourceRef {
  type: 'INTERACTION';
  id: string;
}

/**
 * Trusted provenance example derived directly from public.interactions by the database RPC.
 * SECURITY INVARIANT: Stores strictly metadata (interaction_id, channel, created_at).
 * Message content/text is NEVER stored in examples.
 */
export interface SalesStyleExample {
  interaction_id: string;
  channel: string;
  created_at: string;
}

export const SALES_STYLE_GENERATION_STATUSES = ['DRAFT', 'ACTIVE', 'SUPERSEDED'] as const;
export type SalesStyleGenerationStatus = (typeof SALES_STYLE_GENERATION_STATUSES)[number];

/**
 * Fully persisted record from public.sales_style_profiles.
 */
export interface SalesStyleProfileRecord {
  id: string;
  companyId: string;
  saleUserId: string;
  version: string;
  salutationRules: SalutationRules;
  sentenceStyle: SentenceStyle;
  questionStyle: QuestionStyle;
  objectionStyle: ObjectionStyle;
  closingStyle: ClosingStyle;
  examples: SalesStyleExample[];
  sourceRefs: SalesStyleSourceRef[];
  modelVersion: string | null;
  generationStatus: SalesStyleGenerationStatus;
  createdAt: string;
  updatedAt: string;
}
